### ISSUE TITLE
MockVMAgent Cannot find file

### ISSUE THREAD

**Issue by stefanospan** [PlayFab/LocalMultiplayerAgent#12]
Hello!

So I download mockvmagent and setup the directories as such:
``
"MountPath": "C:\\test",
"LocalFilePath": "C:\\test\\Build10.zip"
"StartGameCommand": "C:\\test\\ExtantServer.exe"
"RunContainer": false,
``

When running the application I get this error in the cmd:
` Creating the configuration file at C:\test\PlayFabVmAgentOutput\2020-07-15T18-00-15\Config\SH0\gsdkConfig.json
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.Azure.Gaming.VmAgent.Common.Interfaces.ProcessWrapper.Start(ProcessStartInfo startInfo) in E:\MPBuildHost14-01\_work\98\s\src\VmAgent\VmAgent.Common\Interfaces\ProcessWrapper.cs:line 32
   at Microsoft.Azure.Gaming.VmAgent.Common.Interfaces.ProcessRunner.CreateAndStart(Int32 instanceNumber, GameResourceDetails gameResourceDetails, ISessionHostManager sessionHostManager) in E:\MPBuildHost14-01\_work\98\s\src\VmAgent\VmAgent.Common\Interfaces\ProcessRunner.cs:line 60
   at Microsoft.Azure.Gaming.MockVmAgent.MultiplayerServerManager.CreateAndStartContainerWaitForExit(SessionHostsStartInfo startParameters) in E:\MPBuildHost14-01\_work\98\s\src\VmAgent\MockVmAgent\MultiplayerServerManager.cs:line 66
   at Microsoft.Azure.Gaming.MockVmAgent.Program.Main(String[] args) in E:\MPBuildHost14-01\_work\98\s\src\VmAgent\MockVmAgent\Program.cs:line 73
   at Microsoft.Azure.Gaming.MockVmAgent.Program.<Main>(String[] `args)``

What's wrong? Thanks!

**Comment by dgkanatsios** [comment]
The error message designates a failure of LocalMultiplayerAgent to start your process. Any chance your paths are not correct? Any permissions issue? Apologies for the inconvenience.

**Comment by mauppi1** [comment]
i'm having the same issue... :(
