### ISSUE TITLE
"AssetDetails" required even for Linux containers on Windows

### ISSUE THREAD

**Issue by RiederAlex** [PlayFab/LocalMultiplayerAgent#9]
Running Linux containers on Windows does not work if "AssetDetails" is not provided, even though it is not needed for deployment.

`Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.Azure.Gaming.MockVmAgent.Config.MultiplayerSettings.ToSessionHostsStartInfo() in D:\Repos\PlayFab\Thunderhead\src\VmAgent\MockVmAgent\Config\MultiplayerSettings.cs:lin
e 49
   at Microsoft.Azure.Gaming.MockVmAgent.Program.Main(String[] args) in D:\Repos\PlayFab\Thunderhead\src\VmAgent\MockVmAgent\Program.cs:line 68
   at Microsoft.Azure.Gaming.MockVmAgent.Program.<Main>(String[] args)`

These are the settings used [MultiplayerSettingsWorking.json.txt](https://github.com/PlayFab/LocalMultiplayerAgent/files/4408851/MultiplayerSettingsWorking.json.txt)

At the moment I'm using the workaround by simply pointing it to a not needed .zip file, see [MultiplayerSettingsNotWorking.json.txt](https://github.com/PlayFab/LocalMultiplayerAgent/files/4408852/MultiplayerSettingsNotWorking.json.txt)

**Comment by dgkanatsios** [comment]
Acknowledged. We have a fix coming, will leave this issue open till it's published. Thanks!

**Comment by dgkanatsios** [comment]
Updated version of LocalMultiplayerAgent, closing for now, let us know if you have any more issues.
